name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ${{ matrix.platform }}
    name: "${{ matrix.platform }} ${{ matrix.toolchain }} RELEASE: ${{ matrix.ENV}}"
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
        ENV: [true, false]
        toolchain: [stable, nightly]
    steps:
      - uses: actions/checkout@v2
      - name: "${{ matrix.toolchain }} with rustfmt, clippy, and wasm32"
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.toolchain }}
          components: rustfmt, clippy
          targets: wasm32-unknown-unknown
      - name: Test
        env:
          NEAR_RELEASE: ${{ matrix.ENV }}
        run: ./ci-test.sh
